#!/usr/bin/env python3
"""Generate CG3 sets for the disambiguator.

Outputs (INCLUDEd by fst/cg3/disambiguator.cg3):
  fst/cg3/generated-sets.cg3 — GenVerb LIST aus valence.json

Akk/Dat-Valenz ist tag-basiert (+GovAkk/+GovDat auf dem Verb, aus
gen_lexc.py). Agreement-Filter sind inline in disambiguator.cg3.
"""

import json
from pathlib import Path

FST_DIR = Path(__file__).resolve().parents[1]
VALENCE_PATH = FST_DIR / "valence.json"
CG3_DIR = FST_DIR / "cg3"

CURATED_GEN_VERBS = ["bijātun", "klausītun", "kwaitītun"]

HEADER = "# AUTOGENERATED by fst/scripts/gen_cg3_sets.py — do not edit.\n"


def verb_lists(valence: dict) -> dict[str, list[str]]:
    by_case = {"Gen": set(CURATED_GEN_VERBS), "Dat": set(), "Acc": set()}
    for v in valence.get("verbs", []):
        lemma = v.get("lemma", "")
        if not lemma:
            continue
        for case in v.get("obj_cases", []):
            if case in by_case:
                by_case[case].add(lemma)
    return {k: sorted(v) for k, v in by_case.items()}


def fmt_list(name: str, lemmas: list[str]) -> str:
    if not lemmas:
        return f'LIST {name} = "__none__" ;\n'
    quoted = " ".join(f'"{lm}"' for lm in lemmas)
    return f"LIST {name} = {quoted} ;\n"


def write_sets(valence: dict):
    lists = verb_lists(valence)
    out = [
        HEADER,
        "# Source: fst/valence.json + kuratierte Gen-Verben.\n\n",
        fmt_list("GenVerb", lists["Gen"]),
    ]
    (CG3_DIR / "generated-sets.cg3").write_text("".join(out), encoding="utf-8")
    return lists


def main():
    valence = json.loads(VALENCE_PATH.read_text(encoding="utf-8"))
    CG3_DIR.mkdir(parents=True, exist_ok=True)
    lists = write_sets(valence)
    print(f"wrote {CG3_DIR}/generated-sets.cg3 "
          f"(GenVerb: {len(lists['Gen'])})")


if __name__ == "__main__":
    main()
