#!/usr/bin/env python3
"""Generate CG3 sets and $$-based agreement rules for the disambiguator.

Outputs (INCLUDEd by fst/cg3/disambiguator.cg3):
  fst/cg3/generated-sets.cg3       — Valenz-LISTs aus valence.json
  fst/cg3/generated-rule1.cg3      — Regel 1: SELECT Adj via $$-Unifikation
  fst/cg3/generated-agreement.cg3  — Agreement-Filter via $$-Unifikation

Die $$-Unifikation expandiert ueber die 24 K×N×G-Signaturen der LIST AGR
(disambiguator.cg3) und arbeitet per LINK-Kette (deterministische Reihenfolge).
1* statt 1**: stoppt am ersten NGHead, ohne weiterzusuchen.
"""

import json
from itertools import product
from pathlib import Path

FST_DIR = Path(__file__).resolve().parents[1]
VALENCE_PATH = FST_DIR / "valence.json"
CG3_DIR = FST_DIR / "cg3"

CURATED_GEN_VERBS = ["bijātun", "klausītun", "kwaitītun"]

HEADER = "# AUTOGENERATED by fst/scripts/gen_cg3_sets.py — do not edit.\n"


def verb_lists(valence: dict) -> dict[str, list[str]]:
    by_case = {"Gen": set(CURATED_GEN_VERBS), "Dat": set(), "Acc": set()}
    for v in valence.get("verbs", []):
        lemma = v.get("lemma", "")
        if not lemma:
            continue
        for case in v.get("obj_cases", []):
            if case in by_case:
                by_case[case].add(lemma)
    return {k: sorted(v) for k, v in by_case.items()}


def fmt_list(name: str, lemmas: list[str]) -> str:
    if not lemmas:
        return f'LIST {name} = "__none__" ;\n'
    quoted = " ".join(f'"{lm}"' for lm in lemmas)
    return f"LIST {name} = {quoted} ;\n"


def write_sets(valence: dict):
    lists = verb_lists(valence)
    out = [
        HEADER,
        "# Source: fst/valence.json + kuratierte Gen-Verben.\n\n",
        fmt_list("GenVerb", lists["Gen"]),
        fmt_list("DatVerb", lists["Dat"]),
        fmt_list("AkkVerb", lists["Acc"]),
    ]
    (CG3_DIR / "generated-sets.cg3").write_text("".join(out), encoding="utf-8")
    return lists


def write_rule1():
    """$$-basierte Regel 1: Token ist Adj, wenn kongruenter Kopf rechts."""
    out = [HEADER,
           "# $$-Unifikation via LIST AGR (disambiguator.cg3).\n\n",
           "SECTION  # Regel 1: Adj bei kongruierendem Kopf rechts\n",
           "SELECT (Adj) IF (0 NAdv) (0 Adj) ",
           "(0 $$AGR LINK 1* NGHead LINK 0 $$AGR) ;\n"]
    (CG3_DIR / "generated-rule1.cg3").write_text("".join(out), encoding="utf-8")


def write_agreement():
    """$$-basierte NG-interne Agreement-Filter."""
    out = [HEADER,
           "# $$-Unifikation via LIST AGR (disambiguator.cg3).\n",
           "# LINK-Kette fuer deterministische $$-Bindung; 1* stoppt an erstem NGHead.\n\n",
           "SECTION  # a) Modifikator <- naechster Nicht-Gen-Kopf\n",
           "REMOVE $$AGR IF (0 AdjNum) ",
           "(0 $$AGR LINK 1* NGHead LINK NOT 0 Gen LINK NEGATE 0 $$AGR) ;\n\n",
           "SECTION  # c) Kopf <- unmittelbar links stehender Modifikator\n",
           "REMOVE $$AGR IF (0 NGHead) ",
           "(0 $$AGR LINK -1 AdjNum LINK NEGATE 0 $$AGR) ;\n\n",
           "SECTION  # b) Modifikator <- naechster Gen-Kopf\n",
           "REMOVE $$AGR IF (0 AdjNum) ",
           "(0 $$AGR LINK 1* NGHead + Gen LINK NEGATE 0 $$AGR) ;\n"]
    (CG3_DIR / "generated-agreement.cg3").write_text("".join(out), encoding="utf-8")


def main():
    valence = json.loads(VALENCE_PATH.read_text(encoding="utf-8"))
    CG3_DIR.mkdir(parents=True, exist_ok=True)
    lists = write_sets(valence)
    write_rule1()
    write_agreement()
    print(f"wrote {CG3_DIR}/generated-{{sets,rule1,agreement}}.cg3 "
          f"(GenVerb: {len(lists['Gen'])}, DatVerb: {len(lists['Dat'])}, "
          f"AkkVerb: {len(lists['Acc'])})")


if __name__ == "__main__":
    main()
