#!/usr/bin/env python3
"""Generate CG3 sets and per-signature agreement rules for the disambiguator.

Outputs (INCLUDEd by fst/cg3/disambiguator.cg3):
  fst/cg3/generated-sets.cg3       — Valenz-LISTs aus valence.json
  fst/cg3/generated-rule1.cg3      — Regel 1: SELECT Adj bei kongruierendem Kopf
  fst/cg3/generated-agreement.cg3  — Agreement-Filter in der NG

Die Agreement-Regeln werden pro Kasus×Numerus×Genus-Signatur ausgeschrieben,
weil vislcg3-$$-Unifikation über mehrere Kontexttests nicht backtrackt
(greedy Bindung am ersten Test), was Existenz-Semantik unmöglich macht.

Präpositionsrektion braucht keine Listen — der FST emittiert +GovAkk/+GovDat.
"""

import json
from itertools import product
from pathlib import Path

FST_DIR = Path(__file__).resolve().parents[1]
VALENCE_PATH = FST_DIR / "valence.json"
CG3_DIR = FST_DIR / "cg3"

# Lexikalisch Gen-regierende Verben aus nominal_group_reference.md
# (Furcht/Begehren/Fehlen/Wahrnehmung); valence.json kennt nur 2 davon.
CURATED_GEN_VERBS = ["bijātun", "klausītun", "kwaitītun"]

COMBOS = [f"{n} {c} {g}"
          for n, c, g in product(("Sg", "Pl"),
                                 ("Nom", "Gen", "Dat", "Akk"),
                                 ("Masc", "Fem", "Neut"))]
NONGEN_COMBOS = [c for c in COMBOS if " Gen " not in f" {c} "]
GEN_COMBOS = [c for c in COMBOS if " Gen " in f" {c} "]

HEADER = "# AUTOGENERATED by fst/scripts/gen_cg3_sets.py — do not edit.\n"


def verb_lists(valence: dict) -> dict[str, list[str]]:
    by_case = {"Gen": set(CURATED_GEN_VERBS), "Dat": set(), "Acc": set()}
    for v in valence.get("verbs", []):
        lemma = v.get("lemma", "")
        if not lemma:
            continue
        for case in v.get("obj_cases", []):
            if case in by_case:
                by_case[case].add(lemma)
    return {k: sorted(v) for k, v in by_case.items()}


def fmt_list(name: str, lemmas: list[str]) -> str:
    if not lemmas:
        # leere LISTs sind in CG3 ein Syntaxfehler — Platzhalter, matcht nie
        return f'LIST {name} = "__none__" ;\n'
    quoted = " ".join(f'"{lm}"' for lm in lemmas)
    return f"LIST {name} = {quoted} ;\n"


def write_sets(valence: dict):
    lists = verb_lists(valence)
    out = [
        HEADER,
        "# Source: fst/valence.json (obj_cases) + kuratierte Gen-Verben aus\n",
        "# prussian-bert docs/nominal_group_reference.md.\n\n",
        fmt_list("GenVerb", lists["Gen"]),
        fmt_list("DatVerb", lists["Dat"]),
        fmt_list("AkkVerb", lists["Acc"]),
    ]
    (CG3_DIR / "generated-sets.cg3").write_text("".join(out), encoding="utf-8")
    return lists


def write_rule1():
    """Doc-Regel 1: Token ist Adj, wenn rechts in der Klausel ein Kopf mit
    passender Signatur steht (Gen-Köpfe transparent via HeadBarrier)."""
    out = [HEADER, "\nSECTION  # Regel 1: Adj bei kongruierendem Kopf rechts\n\n"]
    for c in COMBOS:
        out.append(
            f"SELECT (Adj) IF (0 NAdv) (0 Adj + ({c})) "
            f"(1* NGHead + ({c}) BARRIER HeadBarrier) ;\n")
    (CG3_DIR / "generated-rule1.cg3").write_text("".join(out), encoding="utf-8")


def write_agreement():
    """NG-interne Agreement-Filter: Signaturen entfernen, die mit dem
    relevanten Kopf/Modifikator nicht kongruieren. Nur REMOVE einzelner
    unmöglicher Signaturen — echte Ambiguität bleibt stehen."""
    out = [HEADER, "\nSECTION  # Agreement-Propagation in der NG\n\n"]

    out.append("# a) Sicherer Modifikator ← nächster Nicht-Gen-Kopf:\n"
               "#    Nicht-Gen-Signaturen entfernen, die der Kopf nicht hat.\n"
               "#    Gen-Signaturen bleiben (möglicher Bezug auf Gen-Kopf).\n"
               "#    1**/LINK NOT 0 Gen: kasusambige Gen-Modifikatoren (z.B.\n"
               "#    'Saūlis' Gen|Pl-Nom) werden als Anker übersprungen.\n"
               "#    KEINE Part-Targets: prädikative Partizipien (periphrastisch,\n"
               "#    Aux oft pro-drop) dürfen nicht am Objekt gefiltert werden.\n")
    for c in NONGEN_COMBOS:
        out.append(
            f"REMOVE SAFE AdjNum + ({c}) IF (0C CongrMod) "
            f"(1** NGHead BARRIER AgrBarrier LINK NOT 0 Gen LINK NOT 0 ({c})) ;\n")

    out.append("\n# b) Sicherer Modifikator ← nächster Gen-Kopf:\n"
               "#    Gen-Signaturen entfernen, die der Gen-Kopf nicht hat.\n")
    for c in GEN_COMBOS:
        out.append(
            f"REMOVE SAFE AdjNum + ({c}) IF (0C CongrMod) "
            f"(1* NGHead + Gen BARRIER HeadBarrier LINK NOT 0 ({c})) ;\n")

    out.append("\n# c) Kopf ← unmittelbar links stehender sicherer Modifikator:\n"
               "#    Nicht-Gen-Signaturen entfernen, die der Modifikator nicht hat.\n"
               "#    Nur Adj/Num: prädikative Partizipien (periphrastisch, Aux oft\n"
               "#    pro-drop) modifizieren das folgende Objekt nicht.\n")
    for c in NONGEN_COMBOS:
        out.append(
            f"REMOVE SAFE ({c}) IF (0 NGHead) "
            f"(-1C AdjNum LINK NOT 0 ({c})) ;\n")

    (CG3_DIR / "generated-agreement.cg3").write_text("".join(out), encoding="utf-8")


def main():
    valence = json.loads(VALENCE_PATH.read_text(encoding="utf-8"))
    CG3_DIR.mkdir(parents=True, exist_ok=True)
    lists = write_sets(valence)
    write_rule1()
    write_agreement()
    print(f"wrote {CG3_DIR}/generated-{{sets,rule1,agreement}}.cg3 "
          f"(GenVerb: {len(lists['Gen'])}, DatVerb: {len(lists['Dat'])}, "
          f"AkkVerb: {len(lists['Acc'])}, Signaturen: {len(COMBOS)})")


if __name__ == "__main__":
    main()
